# docker-compose build
version: '2.1'
volumes:
  postgis-data:
#    name: postgis
#    driver: local
#    driver_opts:
#      type: 'none'
#      o: 'bind'
#      device: '/mnt/db/postgis-data'

services:
  db:
    build: .
    user: ${UID}:${GID}
    volumes:
      - postgis-data:/var/lib/postgresql:nocopy
    environment:
      # If you need to create multiple database you can add coma separated databases eg gis,data
      - POSTGRES_DB=${POSTGRES_DBNAME}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASS=${POSTGRES_PASS}
      - ALLOW_IP_RANGE=0.0.0.0/0
      # Add extensions you need to be enabled by default in the DB. Default are the five specified below
      - POSTGRES_MULTIPLE_EXTENSIONS=postgis,hstore,postgis_topology,postgis_raster,pgrouting
    ports:
      - 26432:5432
    restart: on-failure
    healthcheck:
      test: "exit 0"
